### ISSUE TITLE
further documentation

### ISSUE THREAD

**Issue by ghost** [mohlcyber/McAfee-MVISION-ePO-API#1]
Hello,

Is there any documentation around the MVISION ePO API? 
I am looking to discover what the many scope options mean and explore further.

I would like to take maGuid from EDR and translate it into a hostname from ePO.

**Comment by mohlcyber** [comment]
Hi, 

currently we do have some documentation posted here: https://docs.mcafee.com/bundle/mvision-epolicy-orchestrator-product-guide/page/GUID-26C1A6F2-DEB6-48B6-80D6-509649C356BC.html
Anyhow these only include to pull events from the API.

The scenario you described should be possible to do via MVISION API.

All the best,
Martin
