### ISSUE TITLE
Add tenant_id within the Auth API call for enviromemt switch

### ISSUE THREAD

**Issue by jmorillas** [mohlcyber/McAfee-MVISION-ePO-API#4]
Not an issue but a new useful feature. 

#self.tenant_id = 'xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx' # Test
self.tenant_id = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx' # Prod
.
.
.
.
def auth(self):
        data = {
            "username": self.user,
            "password": self.pw,
            "client_id": self.client_id,
            **"tenant_id": self.tenant_id,**
            "scope": self.scope,
            "grant_type": "password"
        }

**Comment by mohlcyber** [comment]
This is great. Thanks for the info. Please make a pull request.
